Update

diff --git a/Rank_2/Push_swap/Checker/Makefile b/Rank_2/Push_swap/Checker/Makefile
--- a/Rank_2/Push_swap/Checker/Makefile
+++ b/Rank_2/Push_swap/Checker/Makefile
@@ -11,23 +11,99 @@
 # **************************************************************************** #
 
 NAME	= checker
-SRC		:= $(wildcard *.c)
-OBJ		= $(SRC:.c=.o)
-CC		= cc
-RM		= rm -f
-CFLAGS	= -g -Wall -Werror -Wextra
 
-all:$(NAME)
+HEADER_LIST = checker.h
+HEADER_DIRECTORY = checker_srcs/
+HEADERS = $(addprefix $(HEADER_DIRECTORY), $(HEADER_LIST))
 
-$(NAME): $(OBJ)
-	$(CC) $(CFLAGS) -o $(NAME) $(OBJ)
+SRCS_LIST = bonus_run_modes.c error_management_bonus.c error_management.c errors_bonus.c \
+main.c moviments.c moviments2.c sort.c proxy.c ft_strchr.c\
+stack_work.c stack_work2.c visualizer.c ft_lstsize_rem.c ft_lstnew_rem.c 
+SRCS_DIRECTORY = checker_srcs/
+SRC = $(addprefix $(SRCS_DIRECTORY), $(SRCS_LIST))
+
+LIBFT_DIRECTORY = ../libft/
+LIBFT_HEADER = $(LIBFT_DIRECTORY)libft.h
+LIBFT = $(LIBFT_DIRECTORY)libft.a
+
+OBJECT_LIST = $(SRCS_LIST:.c=.o)
+OBJECTS_DIRECTORY = objects/
+OBJECTS = $(addprefix $(OBJECTS_DIRECTORY), $(OBJECT_LIST))
+
+CC = cc
+CFLAGS = -g -pthread #-fsanitize=address
+
+LIBS = -L$(LIBFT_DIRECTORY) -lft
+INCLUDES = -I.$(HEADERS) -I.$(LIBFT_HEADER)
+
+# COLORS
+RED     = \033[0;31m
+GREEN   = \033[0;32m
+YELLOW  = \033[0;33m
+GRAY    = \033[1;90m
+RESET   = \033[0m
+
+$(NAME): $(LIBFT) $(OBJECTS_DIRECTORY) $(OBJECTS)
+	@if $(CC) $(CFLAGS) $(INCLUDES) $(OBJECTS) $(LIBS) -o $(NAME); \
+	then \
+		echo "$(GRAY)[" "$(GREEN)OK$(GRAY)" "] | Objects ready!$(RESET)"; \
+		make norm -s; \
+		echo "$(GRAY)[" "$(GREEN)OK$(GRAY)" "] | $(NAME) created!$(RESET)"; \
+	else \
+		echo "$(GRAY)[" "$(RED)Error$(GRAY)" "] | $(RESET)An error occurred while creating checker."; \
+		make fclean; \
+		echo "$(GRAY)[" "$(RED)Error$(GRAY)" "] | $(RESET)All objects Cleaned."; \
+	fi
+
+$(LIBFT):
+	@echo "[" "$(YELLOW)..$(RESET)" "] | Compiling libft..."
+	@make -sC $(LIBFT_DIRECTORY) > /dev/null 2>&1
+	@echo "[" "$(GREEN)OK$(RESET)" "] | Libft ready!"
+
+$(OBJECTS_DIRECTORY)%.o : $(SRCS_DIRECTORY)%.c
+	@$(CC) $(CFLAGS) -c $(INCLUDES) $< -o $@ || (rm -rf $(OBJECTS_DIRECTORY) && exit 1)
+
+$(OBJECTS_DIRECTORY):
+	@echo "$(GRAY)[" "$(YELLOW)..$(GRAY)" "] | Creating objects...$(RESET)"
+	@mkdir -p $(OBJECTS_DIRECTORY)
 
 clean:
-	$(RM)	$(OBJ)
+	@echo "$(GRAY)[" "$(YELLOW)..$(GRAY)" "] | Removing object files...$(RESET)"
+	@rm -rf $(OBJECTS_DIRECTORY)
+	@make -sC $(LIBFT_DIRECTORY) clean > /dev/null 2>&1
+	@echo "$(GRAY)[" "$(GREEN)OK$(GRAY)" "] | Object files removed.$(RESET)"
 
 fclean: clean
-	$(RM)	$(NAME)
+	@echo "$(GRAY)[" "$(YELLOW)..$(GRAY)" "] | Removing binary files...$(RESET)"
+	@rm -rf $(NAME)
+	@make -sC $(LIBFT_DIRECTORY) fclean > /dev/null 2>&1
+	@echo "$(GRAY)[" "$(GREEN)OK$(GRAY)" "] | Binary file removed.$(RESET)"
+
+norm:
+	@echo "$(GRAY)[" "$(YELLOW)..$(GRAY)" "] | Norminetting...$(GRAY)"
+	@if norminette srcs/ | grep -q "Error!" ; then \
+	    echo "$(RESET)[" "$(RED)!!$(RESET)" "] | Norminette found errors."; \
+	    norminette srcs/ | awk '/Error!/ {print "[ " "$(RED)!!$(RESET)" " ] | " $$0}'; \
+	else \
+	    echo "$(GRAY)[" "$(GREEN)OK$(GRAY)" "] | Norminette passed!"; \
+	fi
 
 re: fclean
-	@clear
-	$(MAKE) all
+	clear && make -s
+
+run: re
+	
+
+run_extra: re
+	make -sC Checker
+
+run_die_test: re
+	make -C Checker
+
+val:re
+	valgrind ./$(NAME) 28 59 70 45 19 55 24 96 32 18 49 9 69 25 37 83 33 35 47 31 48 90 64 11 95 71 68 98 86 10 13 3 54 7 8 88 46 52 65 21 66 5 22 76 30 1 89 34 99 2 62 91 26 38 67 94 93 16 73 36 42 79 75 23 80 58 53 14 15 97 40 81 27 20 44 6 61 29 60 56 100 87 77 74 92 63 85 41 12 51 78 84 4 43 50 57 17 39 82 72
+
+val_full:re
+	valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes -s ./$(NAME) arg1 arg2 arg3
+
+.PHONY: all clean fclean re
diff --git a/Rank_2/Push_swap/Makefile b/Rank_2/Push_swap/Makefile
--- a/Rank_2/Push_swap/Makefile
+++ b/Rank_2/Push_swap/Makefile
@@ -10,29 +10,173 @@
 #                                                                              #
 # **************************************************************************** #
 
-NAME	= push_swap
-SRC		:= $(wildcard *.c)
-OBJ		= $(SRC:.c=.o)
-CC		= cc
-RM		= rm -f
-CFLAGS	= -g -Wall -Werror -Wextra
+NAME = push_swap
 
-all:$(NAME)
+HEADER_LIST = push_swap.h
+HEADER_DIRECTORY = srcs/
+HEADERS = $(addprefix $(HEADER_DIRECTORY), $(HEADER_LIST))
 
-$(NAME): run $(OBJ)
-	$(CC) $(CFLAGS) -o $(NAME) $(OBJ)
+SRCS_LIST = main.c error_management_bonus.c error_management.c errors_bonus.c \
+find.c find2.c moviments.c moviments2.c p_decisions.c sort.c sort_conditions.c \
+stack_work.c stack_work2.c ft_lstsize_rem.c ft_lstnew_rem.c sorters.c sort2.c\
+ft_atoi_push.c sort3.c
+SRCS_DIRECTORY = srcs/
+SRC = $(addprefix $(SRCS_DIRECTORY), $(SRCS_LIST))
+
+LIBFT_DIRECTORY = libft/
+LIBFT_HEADER = $(LIBFT_DIRECTORY)libft.h
+LIBFT = $(LIBFT_DIRECTORY)libft.a
+
+OBJECT_LIST = $(SRCS_LIST:.c=.o)
+OBJECTS_DIRECTORY = objects/
+OBJECTS = $(addprefix $(OBJECTS_DIRECTORY), $(OBJECT_LIST))
+
+CC = cc
+CFLAGS = -g -pthread #-fsanitize=address
+
+LIBS = -L$(LIBFT_DIRECTORY) -lft
+INCLUDES = -I.$(HEADERS) -I.$(LIBFT_HEADER)
+
+# COLORS
+RED     = \033[0;31m
+GREEN   = \033[0;32m
+YELLOW  = \033[0;33m
+GRAY    = \033[1;90m
+RESET   = \033[0m
+
+$(NAME): $(LIBFT) $(OBJECTS_DIRECTORY) $(OBJECTS)
+	@if $(CC) $(CFLAGS) $(INCLUDES) $(OBJECTS) $(LIBS) -o $(NAME); \
+	then \
+		echo "$(GRAY)[" "$(GREEN)OK$(GRAY)" "] Objects ready!$(RESET)"; \
+		make norm -s; \
+		echo "$(GRAY)[" "$(GREEN)OK$(GRAY)" "] $(NAME) created!$(RESET)"; \
+	else \
+		echo "$(GRAY)[" "$(RED)Error$(GRAY)" "] $(RESET)An error occurred while creating push_swap."; \
+		make fclean; \
+		echo "$(GRAY)[" "$(RED)Error$(GRAY)" "] $(RESET)All objects Cleaned."; \
+	fi
+
+$(LIBFT):
+	@echo "$(GRAY)[" "$(YELLOW)..$(GRAY)" "] Compiling libft...$(RESET)"
+	@make -sC $(LIBFT_DIRECTORY) > /dev/null 2>&1
+	@echo "$(GRAY)[" "$(GREEN)OK$(GRAY)" "] Libft ready!$(RESET)"
+
+$(OBJECTS_DIRECTORY)%.o : $(SRCS_DIRECTORY)%.c
+	@$(CC) $(CFLAGS) -c $(INCLUDES) $< -o $@ || (rm -rf $(OBJECTS_DIRECTORY) && exit 1)
+
+$(OBJECTS_DIRECTORY):
+	@echo "$(GRAY)[" "$(YELLOW)..$(GRAY)" "] Creating objects...$(RESET)"
+	@mkdir -p $(OBJECTS_DIRECTORY)
+
+bonus:
+	@echo "[" "$(YELLOW)..$(RESET)" "] Compiling Checker..."
+	@make -sC Checker/ > /dev/null 2>&1
+	@echo "[" "$(GREEN)OK$(RESET)" "] Checker ready!"
+
 
 clean:
-	$(RM)	$(OBJ)
-	make -C Checker clean
+	@echo "$(GRAY)[" "$(YELLOW)..$(GRAY)" "] Removing object files...$(RESET)"
+	@rm -rf $(OBJECTS_DIRECTORY)
+	@make -sC $(LIBFT_DIRECTORY) clean > /dev/null 2>&1
+	@make -sC Checker clean > /dev/null 2>&1
+	@echo "$(GRAY)[" "$(GREEN)OK$(GRAY)" "] Object files removed.$(RESET)"
 
 fclean: clean
-	$(RM)	$(NAME)
-	make -C Checker fclean
+	@echo "$(GRAY)[" "$(YELLOW)..$(GRAY)" "] Removing binary files...$(RESET)"
+	@rm -rf $(NAME)
+	@make -sC $(LIBFT_DIRECTORY) fclean > /dev/null 2>&1
+	@make -sC Checker fclean > /dev/null 2>&1
+	@$(RM) Push-Swap-Tester/push_swap > /dev/null 2>&1
+	@echo "$(GRAY)[" "$(GREEN)OK$(GRAY)" "] Binary file removed.$(RESET)"
+
+norm:
+	@echo "$(GRAY)[" "$(YELLOW)..$(GRAY)" "] Norminetting...$(GRAY)"
+	@if norminette srcs/ | grep -q "Error!" ; then \
+	    echo "$(RESET)[" "$(RED)!!$(RESET)" "] Norminette found errors."; \
+	    norminette srcs/ | awk '/Error!/ {print "[ " "$(RED)!!$(RESET)" " ] " $$0}'; \
+	else \
+	    echo "$(GRAY)[" "$(GREEN)OK$(GRAY)" "] Norminette passed!"; \
+	fi
+
+install_visualizer:
+	@if [ ! -d push_swap_visualizer ]; then \
+		echo "$(RESET)[" "$(YELLOW)..$(RESET)" "] Cloning push_swap_visualizer...$(RESET)"; \
+		git clone https://github.com/o-reo/push_swap_visualizer.git > /dev/null 2>&1; \
+		if [ -d push_swap_visualizer ]; then \
+			echo "$(RESET)[" "$(GREEN)OK$(RESET)" "] push_swap_visualizer Cloned Successfully!$(RESET)"; \
+		else \
+			echo "$(RESET)[" "$(RED)Error$(RESET)" "] $(RED)Failed to Clone push_swap_visualizer!$(RESET)"; \
+			exit 1; \
+		fi \
+	else \
+		echo "$(GRAY)[" "$(GREEN)OK$(GRAY)" "] push_swap_visualizer Already Cloned!$(RESET)"; \
+	fi
+
+	@if [ ! -d push_swap_visualizer/build ]; then \
+		echo "$(RESET)[" "$(YELLOW)..$(RESET)" "] Creating build Folder...$(RESET)"; \
+		mkdir -p push_swap_visualizer/build; \
+		if [ -d push_swap_visualizer/build ]; then \
+			echo "$(RESET)[" "$(GREEN)OK$(RESET)" "] build Folder Created!$(RESET)"; \
+		else \
+			echo "$(RESET)[" "$(RED)Error$(RESET)" "] Failed to Create build Folder!$(RESET)"; \
+			exit 1; \
+		fi \
+	else \
+		echo "$(GRAY)[" "$(GREEN)OK$(GRAY)" "] build Folder Already Exists!$(RESET)"; \
+	fi
+
+	echo "$(RESET)[" "$(YELLOW)..$(RESET)" "] Executing cmake...$(RESET)"; \
+	cmake -S push_swap_visualizer -B push_swap_visualizer/build > /dev/null 2>&1; \
+	if [ -d push_swap_visualizer/build/CMakeFiles ]; then \
+		echo "$(RESET)[" "$(GREEN)OK$(RESET)" "] cmake Executed Successfully!$(RESET)"; \
+	else \
+		echo "$(RESET)[" "$(RED)Error$(RESET)" "] cmake Failed!$(RESET)"; \
+		exit 1; \
+	fi \
+
+	echo "$(RESET)[" "$(YELLOW)..$(RESET)" "] Setting up push_swap_visualizer...$(RESET)"; \
+	make -s -C push_swap_visualizer/build
+
+
+install_tester:
+	git clone https://github.com/gemartin99/Push-Swap-Tester.git
+	sudo apt-get install ruby -y
 
 re: fclean
-	@clear
-	$(MAKE) all
+	clear && make -s
 
-run:
-	make -C Checker
+run_visualizer: $(NAME)
+	@if [ -x push_swap_visualizer/build/bin/visualizer ]; then \
+		echo "$(GRAY)[" "$(GRAY)..$(GRAY)" "] Running push_swap_visualizer!$(RESET)"; \
+	else \
+		echo "$(RESET)[" "$(YELLOW)!!$(RESET)" "] Installing push_swap_visualizer...$(RESET)"; \
+		$(MAKE) -s install_visualizer; \
+		echo "$(RESET)[" "$(GREEN)OK$(RESET)" "] push_swap_visualizer Installed!$(RESET)"; \
+	fi
+	@cd push_swap_visualizer/build && ./bin/visualizer;
+
+run_tester: $(NAME)
+	@if [ ! -d Push-Swap-Tester ]; then \
+		echo "$(GRAY)[" "$(YELLOW)..$(GRAY)" "] Installing Push-Swap-Tester...$(RESET)"; \
+		$(MAKE) install_tester; \
+		echo "$(GRAY)[" "$(GREEN)OK$(GRAY)" "] Push-Swap-Tester Installed!$(RESET)"; \
+	else \
+		echo "$(GRAY)[" "$(YELLOW)..$(GRAY)" "] Running Push-Swap-Tester!$(RESET)"; \
+	fi; \
+	@cp push_swap /mnt/c/Users/ASUS/OneDrive/Documents/INFORMATICA/My_projects-1/42_projects/Rank_2/Push_swap/Push-Swap-Tester; \
+	@cd Push-Swap-Tester/ && bash push_swap_test_linux.sh 100 100;
+
+run_checker: $(NAME)
+	@make -sC Checker
+	@ARG="28 59 70 45 19"; ./push_swap $$ARG | ./Checker/checker $$ARG
+
+run: $(NAME)
+	./$(NAME) 28 59 70 45 19 55 24 96 32 18 49 9 69 25 37 83 33 35 47 31 48 90 64 11
+
+val:re
+	valgrind ./$(NAME) 28 59 70 45 19 55 24 96 32 18 49 9 69 25 37 83 33 35 47 31 48 90 64 11 95 71 68 98 86 10 13 3 54 7 8 88 46 52 65 21 66 5 22 76 30 1 89 34 99 2 62 91 26 38 67 94 93 16 73 36 42 79 75 23 80 58 53 14 15 97 40 81 27 20 44 6 61 29 60 56 100 87 77 74 92 63 85 41 12 51 78 84 4 43 50 57 17 39 82 72 
+
+val_full: $(NAME)
+	valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes -s ./$(NAME) 28 59 70 45 19 55 24 96 32 18 49 9 69 25 37 83 33 35 47 31 48 90 64 11 95 71 68 98 86 10 13 3 54 7 8 88 46 52 65 21 66 5 22 76 30 1 89 34 99 2 62 91 26 38 67 94 93 16 73 36 42 79 75 23 80 58 53 14 15 97 40 81 27 20 44 6 61 29 60 56 100 87 77 74 92 63 85 41 12 51 78 84 4 43 50 57 17 39 82 72 
+
+.PHONY: all clean fclean re
diff --git a/Rank_2/So_Long/Makefile b/Rank_2/So_Long/Makefile
--- a/Rank_2/So_Long/Makefile
+++ b/Rank_2/So_Long/Makefile
@@ -13,10 +13,12 @@
 NAME = so_long
 TEXTURE_C =
 ANIMATION_C = player_look.c player_walk.c collectibles_animations.c \
-	floor_animations.c wall_animations.c exit_animation.c
+	floor_animations.c wall_animations.c exit_animation.c \
+	player_look2.c player_walk2.c collectibles_animations2.c \
+	floor_animations2.c wall_animations2.c exit_animation2.c
 MAP_C = map_validation.c map_validation2.c read_map.c
-EVENTS_C = base_movs.c keycode.c prints.c
-INTERFACE_C = window.c main_image.c pixeis.c destroy_window.c destroy_window2.c\
+EVENTS_C = base_movs_left_right.c base_movs_up_down.c base_movs_left_right2.c base_movs_up_down2.c keycode.c prints.c
+INTERFACE_C = window.c main_image.c main_image2.c pixeis.c destroy_window.c destroy_window2.c\
 		vals_init.c secundary_images_adjusts.c secundary_images_adjusts_2.c
 
 LIBFT_DIRECTORY = libft/
@@ -69,9 +71,16 @@ YELLOW  = \033[0;33m
 RESET   = \033[0m
 
 $(NAME): $(LIBFT) $(MLX) $(OBJECTS_DIRECTORY) $(OBJECTS)
-	@$(CC) $(CFLAGS) $(INCLUDES) $(OBJECTS) $(LIBS) -o $(NAME)
-	@make norm -s
-	@echo "[" "$(GREEN)OK$(RESET)" "] | so_long created!"
+	@$(CC) $(CFLAGS) $(INCLUDES) $(OBJECTS) $(LIBS) -o $(NAME); \
+	if [ $$? = 0 ]; then \
+		echo "$(GRAY)[" "$(GREEN)OK$(GRAY)" "] | Objects ready!$(RESET)"; \
+		make norm -s; \
+		echo "$(GRAY)[" "$(GREEN)OK$(GRAY)" "] | $(NAME) created!$(RESET)"; \
+	else \
+		echo "$(GRAY)[" "$(RED)Error$(GRAY)" "] | $(RESET)An error occurred while creating push_swap."; \
+		make fclean; \
+		@echo "[" "$(GREEN)OK$(RESET)" "] | so_long created!"; \
+	fi
 
 $(OBJECTS_DIRECTORY):
 	@echo "[" "$(YELLOW)..$(RESET)" "] | Creating objects..."
@@ -91,7 +100,6 @@ $(LIBFT):
 	@make -sC $(LIBFT_DIRECTORY) > /dev/null 2>&1
 	@echo "[" "$(GREEN)OK$(RESET)" "] | Libft ready!"
 
-
 $(MLX):
 	@echo "[" "$(YELLOW)..$(RESET)" "] | Compiling minilibx..."
 	@cd $(MLX_DIRECTORY) && bash configure > /dev/null 2>&1
@@ -106,28 +114,30 @@ clean:
 fclean: clean
 	@echo "[" "$(YELLOW)..$(RESET)" "] | Removing binary files...$(RESET)"
 	@rm -rf $(NAME)
-	@make -sC $(LIBFT_DIRECTORY) fclean > /dev/null 2>&1
 	@rm -rf $(MLX)
 	@echo "[" "$(GREEN)OK$(RESET)" "] | Binary file removed."
 
 norm:
 	@echo "[" "$(YELLOW)..$(RESET)" "] | Norminetting...$(RESET)"
 	@if norminette srcs/ libft/ images/ | grep -q "Error!" ; then \
-	    echo "[" "$(RED)!!$(RESET)" "] | Norminette found errors.$(RESET)"; \
-	    norminette srcs/ libft/ images/ | awk '/Error!/ {print "[ " "$(RED)!!$(RESET)" " ] | " $$0}'; \
+		echo "[" "$(RED)!!$(RESET)" "] | Norminette found errors.$(RESET)"; \
+		norminette srcs/ libft/ images/ | awk '/Error!/ {print "[ " "$(RED)!!$(RESET)" " ] | " $$0}'; \
 	else \
-	    echo "[" "$(GREEN)OK$(RESET)" "] | Norminette passed!"; \
+		echo "[" "$(GREEN)OK$(RESET)" "] | Norminette passed!"; \
 	fi
 
 re: fclean
 	clear && make -s
 
-run: re
-	./so_long mapa3.ber
+run: $(NAME)
+	./so_long progressive3.ber
 
-multi_run: re
-	./so_long progressive.ber progressive2.ber progressive5.ber progressive4.ber \
-		progressive3.ber progressive6.ber 42_logo.ber
+42_run: $(NAME)
+	./so_long cluster1.ber cluster2.ber 42_logo.ber
+
+progressive_run: $(NAME)
+	./so_long progressive.ber progressive2.ber progressive5.ber progressive4.ber progressive3.ber \
+		progressive6.ber 42_logo.ber
 
 multi_full_valgrind: re
 	valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes -s ./so_long \
@@ -136,19 +146,19 @@ multi_full_valgrind: re
 
 map3:./so_long mapa3.ber
 
-dbug: re
+dbug: $(NAME)
 	gdb -tui -args ./so_long mapa.ber mapa4.ber
 
-val:re
-	valgrind ./so_long mapa3.ber mapa4.ber
+val:$(NAME)
+	valgrind ./so_long progressive3.ber
 
-val2:re
+val2:$(NAME)
 	valgrind ./so_long mapa.ber mapa4.ber
 
-val_full:re
+val_full:$(NAME)
 	valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes -s ./so_long mapa3.ber
 
-val_full2:re
+val_full2:$(NAME)
 	valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes -s ./so_long mapa.ber
 
 
